[categories]
MIS = [
    "informatie behoefte",
    "Requirements en Informatie",
    "Dashboard in Power BI",
    "ICT systemen",
    "Balanced Scorecard",
    "Cloud",
    "AI",
]
MAC = [
    "Type onderneming",
    "organisatie",
    "budget omzet",
    "kostprijs",
    "verschillen-analyse",
]
KMT = [
    "Statistische analyses",
]
CAT = [
    "Start CAT",
    "CAT/ Adviesrapport",
]
