project:
  type: website

website:
  title: "OPM - Operations"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: werkwijze.qmd
        text: Werkwijze

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
